services:
  - type: web
    name: shl-assessment-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /
    domains:
      - shl-assessment-api.onrender.com
    plan: starter # Specifies the free tier
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    resources:
      cpu: 0.25
      memory: 512Mi 